version: "3"
services:

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGHOST: db
      PGUSER: postgres
      PGPASSWORD: JABc7jERGQKdvMSV
      PGDATABASE: postgres

  db:
    build: db
    environment:
      POSTGRES_PASSWORD: JABc7jERGQKdvMSV
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
