version: "3"
services:

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      PGCONNECTION: postgres://postgres:JABc7jERGQKdvMSV@db/postgres

  db:
    build: db
    environment:
      POSTGRES_PASSWORD: JABc7jERGQKdvMSV
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
